### ISSUE TITLE
Избегание столкновений: Неверно задана высота точек маршрута или уровня моря

### ISSUE THREAD

**Issue by deadln** [acsl-mipt/drone-games#10]
Координаты точек маршрута имеют вид:
1.0046790641871626 1.0009882945059274 121.0
1.0050389922015597 1.0007187596801768 131.0
1.004769046190762 1.0003593798252748 115.0
1.0044091181763648 1.000628914659671 105.0
1.0041391721655668 1.000269534843038 115.0
1.004499100179964 1.0 105.0
1.0048590281943612 0.9997304651273407 120.0
1.0045890821835632 0.99937108532305 115.0

Глобальные координаты коптера в точке взлёта выглядят вот так:
![Снимок экрана от 2021-11-15 22-24-48](https://user-images.githubusercontent.com/44840386/141844267-f79d449d-0388-4929-b710-24a44045f358.png)
Слева высота из топика _global_position/global_ равна 232. Справа - преобразованная в программе высота равна 216. Я осведомлён, что высота, выдаваемая MAVROS, задана в элипсоиде WGS-84. Я преобразую её в высоту над уровнем моря(AMSL), вычисляя разницу с помощью этой [функции](https://wiki.ros.org/mavros#mavros.2FPlugins.Avoiding_Pitfalls_Related_to_Ellipsoid_Height_and_Height_Above_Mean_Sea_Level), а затем отнимая эту разницу от эллипсоидной высоты. Однако даже после такого преобразования точки маршрута оказываются ниже уровня земли, и дрон при попытке приблизиться к любой точке врезается в землю.

**Comment by korotkoves** [comment]
Ошибка исправлена, см. [CHANGELOG](https://github.com/acsl-mipt/drone-games/blob/main/CHANGELOG.md).

**Comment by deadln** [comment]
Всё теперь работает, спасибо за оперативность
