### ISSUE TITLE
Дрон не встает в необходимую позицию

### ISSUE THREAD

**Issue by KatsuShooter** [acsl-mipt/drone-games#2]
![Screenshot_from_2021-03-30_12-46-00](https://user-images.githubusercontent.com/23191791/113032992-50c18c80-91b2-11eb-8a5d-c95bf5247432.png)

После запуска скрипта 6 дрон не встает в заданную ему точку.

**Comment by vadim-rm** [comment]
Присоединяюсь к проблеме, не спавнится шестой дрон, иногда пятый. Перезагрузка не помогает, выполнение stop.sh тоже

**Comment by MaximTar** [comment]
Проблема уже локализована, сейчас в процессе исправления. Всем участникам придет оповещение, когда нужно будет обновиться.

**Comment by korotkoves** [comment]
Проблема с появлением дронов в симуляции решена. Необходимо обновиться (git pull) и выполнить ./install.sh update
