### ISSUE TITLE
Загрузка аппаратов

### ISSUE THREAD

**Issue by MKargus0** [acsl-mipt/drone-games#3]
Во время загрузки симулятора возникает проблема при спавне ЛА. Иногда, борта не прогружаются, в связи с чем нет возможности запустить симуляцию. Проблема возникает на разных системах, даже на достаточно мощном железе. По логам отслеживаем следующие ошибки (скрин 1). В некоторых случаях симуляция запускается (что бывает достаточно редко, примерно раза с 6). Также данная ошибка возникает непосредственно при полёте ЛА.
![Screenshot from 2021-04-01 21-48-56](https://user-images.githubusercontent.com/48154519/113340312-619a0b80-9334-11eb-8e30-959bdd41e62b.png)
 
P.s. Установка других версий protobuf, с последующей пересборкой проблему не решает.
Проблем схожая с предыдущим issue, однако решили дополнить.

([ 4816.437163] gzserver[86689]: segfault at 24 ip 00007f456e9005d4 sp 00007f44d5bf5228 error 4 in libprotobuf.so.17.0.0[7f456e7c7000+1a8000]
[ 4816.437172] Code: 24 48 8b 7d 00 eb ac e8 2a 75 ec ff 48 8d 3d 93 ef 06 00 e8 ee 73 ec ff f3 0f 1e fa 49 89 c4 e9 28 4d ed ff 66 90 f3 0f 1e fa <48> 8b 06 48 85 c0 0f 84 c8 00 00 00 41 55 41 54 55 53 48 83 ec 08
)

**Comment by MKargus0** [comment]
В коммите a0bc218375f6041eed2819d3dcb2caa1ffefdc1e  отсутствует проблема с отановкой симуляции в полете , однако проблема с загрузкой аппаратов все еще присутствует.

**Comment by korotkoves** [comment]
Проблема с появлением дронов в симуляции решена. Необходимо обновиться (git pull) и выполнить ./install.sh update
