### ISSUE TITLE
Проблема с работой симулятора, после обновления

### ISSUE THREAD

**Issue by MKargus0** [acsl-mipt/drone-games#4]
После обновления проблема не разрешилась, периодически возникают ошибки при работе симулятора. Дроны стали чащи прогружаться и вставать на свои места, но время в симуляторе всё также останавливается, а также сам симулятор иногда вылетает. На скриншотах приведённых ниже показано, как остановилось время в симуляторе и соответсвующая ошибка. Пробовали запускать симулятор без написанной нами программы(error1_0, error1_1), ошибки всё те же.
![error1_0](https://user-images.githubusercontent.com/48154519/113427271-6797f700-93dd-11eb-9f8c-06409f34e248.png)
![error1_1](https://user-images.githubusercontent.com/48154519/113427278-6961ba80-93dd-11eb-819d-82dfad83f2d2.png)
Остановка симуляции при работе программы для управления группой ЛА:
![error2_0](https://user-images.githubusercontent.com/48154519/113427284-6bc41480-93dd-11eb-988d-f3954cef7143.png)

**Comment by korotkoves** [comment]
Выложена новая версия, см. историю изменений и главу про системы координат в заданиях.
