### ISSUE TITLE
Не работают гонки

### ISSUE THREAD

**Issue by deadln** [acsl-mipt/drone-games#5]
Установил рабочее окружение на не виртуальную систему. ПК соответствует системным требованиям. Скрипты _start.sh_ и _test-group.sh_ работают без проблем. Но при попытке запустить скрипт _race.sh_ симуляция не запускается в следующих вариациях:

- `./race.sh nonprof mc` - gazebo запускается, но не успев прогрузить мир вылетает
- `./race.sh prof mc` - ничего не происходит
- `./race.sh nonprof vtol` - первые несколько раз симуляция запускалась и даже расставляла vtol-ы, но при этом через некоторое время самопроизвольно закрывалась(или же вылетала). Теперь gazebo просто запускается, но не прогружает мир и вылетает
- `./race.sh prof vtol` - ничего не происходит

Также я запечатлел отчёт о вылете gazebo
![Снимок экрана от 2021-04-03 12-08-31](https://user-images.githubusercontent.com/44840386/113474944-906ec980-947b-11eb-9f66-0e743f604986.png)
![Снимок экрана от 2021-04-03 12-08-48](https://user-images.githubusercontent.com/44840386/113474949-95cc1400-947b-11eb-94c7-6e686ffaac3d.png)
![Снимок экрана от 2021-04-03 12-09-09](https://user-images.githubusercontent.com/44840386/113474952-99f83180-947b-11eb-8b9e-45dc607be796.png)
![Снимок экрана от 2021-04-03 12-09-21](https://user-images.githubusercontent.com/44840386/113474956-9ebce580-947b-11eb-993a-74dd324bb233.png)
![Снимок экрана от 2021-04-03 12-09-29](https://user-images.githubusercontent.com/44840386/113474960-a11f3f80-947b-11eb-8fc6-eab4d497bdf6.png)
И сообщение которое выводится при прерывании скрипта _race.sh_
![Снимок экрана от 2021-04-03 13-06-51](https://user-images.githubusercontent.com/44840386/113475320-9796d700-947d-11eb-80cc-2760fac6e48c.png)
Никаких скриптов для гонки я не писал. Мне наоборот интересно, как именно привязывать скрипт к симуляции(не нашёл конкретного ответа ни в задании, ни в FAQ). Просто положить его в папку _race_?

**Comment by IgorGoryainov** [comment]
Такая же проблема.

**Comment by deadln** [comment]
Я нашёл способ запуска скрипта полёта в симуляции гонки. Я модифицировал файл _race.sh_, добавив в его конец:
```
mode="mc"
if [model == "standard_vtol"]; then
  mode="vtol"
fi
./examples/group.py $mode
```
В результате при запуске `./race.sh` с параметрами либо `nonprof mc [кол-во дронов]`, либо `nonprof vtol [кол-во дронов]` симуляция запускается, расставляет дроны, и первые три дрона даже взлетают и выполняют полёт по скрипту _examples/group.py_. Однако симуляция всё ещё нестабильна и может вылететь в любой момент по неизвестной причине. Но я также заметил, что при вылете gazebo в консоли продолжается вывод информации. Лишь однажды вывод в консоли прервался из-за какой-то ошибки, которую я не запечатлел и не могу сейчас воспроизвести. Что касается запусков в режиме профессиональной лиги, то они всё также не работают и ничего не выводят.

**Comment by deadln** [comment]
Пока профессиональная лига сломана, приходится играться в любительской. По моим ощущениям, если начать двигать камеру в симуляторе до взлёта, то это многократно увеличивает шанс вылета симулятора. Да и после взлёта симулятор как будто работает стабильнее если его не трогать

**Comment by deadln** [comment]
Через определнённое количество запусков симуляция может сломаться, и не запускаться совсем в том или ином виде. Помогает полное удаление папки с симуляцией и переустановка

**Comment by deadln** [comment]
В скрипте _race.sh_ я приписал параметр для включения дебага Gazebo. Однако при вылете в терминалах ничего особенного не появляется
![Снимок экрана от 2021-04-07 14-57-59](https://user-images.githubusercontent.com/44840386/113862927-b369e800-97b1-11eb-8abf-1fa822180db9.png)

**Comment by korotkoves** [comment]
Выложена новая версия, см. историю изменений и главу про системы координат в заданиях.
