### ISSUE TITLE
Некорректная работа большого количества дронов

### ISSUE THREAD

**Issue by KatsuShooter** [acsl-mipt/drone-games#6]
После обновления, больше 20 дронов начинают неправильно работать и хаотично двигаться. До 20 дронов все работает корректно. 

![6 drones](https://user-images.githubusercontent.com/23191791/114067108-42fcbd00-98be-11eb-9d0f-664de0658421.png)

![27 drones](https://user-images.githubusercontent.com/23191791/114067045-2e202980-98be-11eb-9d57-0b337ad78f68.png)

Периодически возникает ошибка в консоли: 
![cmd](https://user-images.githubusercontent.com/23191791/114067304-7f301d80-98be-11eb-9ce4-4e79e96bdfe3.png)

До обновления все работало корректно.

**Comment by MaximTar** [comment]
> После обновления, больше 20 дронов начинают неправильно работать и хаотично двигаться. До 20 дронов все работает корректно.

Это связано с недостатком вычислительных ресурсов. На втором скриншоте видно, что проседает RTF. 

> До обновления все работало корректно.

Ранее была другая проблема, связанная с lockstep-симуляцией, которая часто работает некорректно с большим количеством аппаратов. Поэтому она была отключена. [Подробнее про lockstep-симуляцию.](https://docs.px4.io/master/en/simulation/#lockstep-simulation) 
По ссылке вы также можете узнать, почему теперь критически важным для работы является значение RTF.

> Периодически возникает ошибка в консоли:

Данная ошибка, насколько я могу судить по скриншоту, возникает уже в вашем скрипте.
