### ISSUE TITLE
Проблемы с симуляцией в гонках

### ISSUE THREAD

**Issue by deadln** [acsl-mipt/drone-games#7]
1. При пролёте через препятствие в топике не всегда сразу публикуется следующая стена. Хоть на такой случай мы и прописали обработку ошибок, но эта проблема долгое время сводила дроны с ума
![Ошибка](https://user-images.githubusercontent.com/44840386/114438352-4ea6f700-9bd0-11eb-887a-258d88d5b102.png)
2. Если дрон упирается в стену, то его телеметрия сходит с ума
![Снимок экрана от 2021-04-12 20-27-35](https://user-images.githubusercontent.com/44840386/114438861-fb817400-9bd0-11eb-969c-d9cf8e9e5999.png)
3. Иногда дроны просто не взлетают, или взлетают с запозданием
4. Через определённое количество запусков симуляция перестаёт запускаться. Помогает полное удаление папки с симуляцией и переустановка и/или перезагрузка компьютера

**Comment by korotkoves** [comment]
>     1. При пролёте через препятствие в топике не всегда сразу публикуется следующая стена. Хоть на такой случай мы и прописали обработку ошибок, но эта проблема долгое время сводила дроны с ума
Частота публикации в топике 2 Гц (то есть время реакции 0.5 сек). Повысили до 5Гц
> 
>     2. Если дрон упирается в стену, то его телеметрия сходит с ума
Такое возможно в симуляции, особенно на больших скоростях аппарата.

> 
>     3. Иногда дроны просто не взлетают, или взлетают с запозданием
см. пояснения ниже

> 
>     4. Через определённое количество запусков симуляция перестаёт запускаться. Помогает полное удаление папки с симуляцией и переустановка и/или перезагрузка компьютера
Папка с симуляцией никак не может влиять на успешность запуска, переустановка тем более.
Удаление рабочей директории workspace может повлиять, но скрипт запуска симуляции все равно генерирует файлы заново независимо от ее содержания. Если перезагрузка помогла, возможно в памяти висели не убитые процессы.

Так же следует учитывать следующее:
1) После запуска симуляции телеметрия может некоторое время отсутствовать пока запускается фильтр положения  в автопилоте. Необходимо подождать некоторое время до появления телеметрии у всех.
2) В силу погрешности фильтр может выдавать не точное значение положения, а его приближенное. Например при расстановке коптеров, координата z может уйти в небольшой минус.
