### ISSUE TITLE
Индивидуальный центр координат у каждого дрона

### ISSUE THREAD

**Issue by deadln** [acsl-mipt/drone-games#9]
Ближе к вечеру вчерашнего дня я начал замечать что некоторые дроны ведут себя странно. Посмотрев на данные их телеметрии я понял, что по какой-то причине они считают своим началом координат не центр взлётной площадки, а то место где они появились. По началу это происходило только с отдельными дронами, но потом "болезнь" захватила все аппараты. Подобное поведение проявляется и на моей машине, и на удалённом компьютере. Я предполагал что это может быть вызвано моим кодом, но откат на коммит где всё идеально работало ничего не изменил. Пришлось писать функционал для корректировки координат каждого дрона под координаты трассы. Но дроны всё равно ведут себя странно, хоть и не все.
Что это, загадочной природы (появился не из-за обновления репозитория соревнования) баг? Или же секретная фича с таймером? Как по мне, хотелось бы вернуть всё как было, когда у дронов была единая координатная сетка с центром в центре взлётной площадки.

**Comment by deadln** [comment]
До меня дошло что именно за странное поведение у дронов. Возможно на мгновение их координатная сетка возвращается к координатам симулятора. За это мгновение дрон решает что он уже пролетел стену. Но так как на самом деле этого не произошло и данные о следующей стене не были получены, он зависает. Отвисает он лишь тогда, когда другой дрон пролетает стену и провоцирует появление данных о новой стене.

**Comment by korotkoves** [comment]
Координатная сетка **должна** совпадать с координатной сеткой аппаратов (в системе симуляции сделаны спец. правки).
Она не совпадает (ноль системы аппарата в месте его включения) только некоторое время после появления аппарата в симуляции. Если это не так и координаты аппарата остаются нулевыми длительное время, сообщите, будем исправлять.

**Comment by deadln** [comment]
> Координатная сетка **должна** совпадать с координатной сеткой аппаратов (в системе симуляции сделаны спец. правки).
> Она не совпадает (ноль системы аппарата в месте его включения) только некоторое время после появления аппарата в симуляции. Если это не так и координаты аппарата остаются нулевыми длительное время, сообщите, будем исправлять.

@korotkoves К сожалению, это не так, координаты большинства аппаратов считают нулём координат то место где они появились на протяжении всего полёта. Чтобы компенсировать этот баг мне приходится корректировать их телеметрию используя координаты их стартовой расстановки в файле `places.txt`

**Comment by korotkoves** [comment]
Сообщите тогда как запускалась симуляция, чтобы можно было повторить этот баг у себя.

**Comment by deadln** [comment]
Баг случается в гонке в профессиональной лиге на обеих трассах и вне зависимости от того задан ли файл стартовых расстановок дронов

**Comment by deadln** [comment]
Вы не поверите, но я нашёл причину бага. Моя программа посылала дронам сигналы чтобы они армились сразу же после запуска программы. Как только я прописал арминг и OFFBOARD через 15 секунд после запуска программы, баг исчез. Видимо если это делать сразу, то симуляция "забывает" назначить дрону истинные координаты.

**Comment by korotkoves** [comment]
Симуляция ничего не забывает, как я написал выше некоторое время после запуска симуляции, аппараты имеют координаты 0,0,0, далее они резко меняются на правильные. Если в этом промежутке запускать внешнее управление аппаратом, то инициализируется неправильный ноль.
Обновил код репозитария, чтобы не надо было ждать 15 секунд, и сразу можно было запускать свой скрипт управления после запуска симуляции. Необходимо сделать ./install.sh update
